site_name: griddler

nav:
  - index.md
  - core_concepts.md
  - griddles.md
  - reference.md

repo_url: https://github.com/cdcgov/pygriddler
repo_name: repo

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            extra:
              show_root_heading: true
              show_full_root_path: true
  - search
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - admonition
