site_name: griddler

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_full_root_path: true
- search

nav:
  - index.md
  - API reference: reference.md
