[tool.poetry]
name = "griddler"
version = "0.1.0"
description = ""
authors = ["Scott Olesen <ulp7@cdc.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.1"
polars = {version = "^1.7.1", optional = true}
pytest = "^8.2.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
mkdocs = "^1.6.0"
mkdocstrings = {extras = ["python"], version = "^0.25.1"}
mkdocs-material = "^9.5.28"
mkdocstrings-python = "^1.10.5"
mdx-truly-sane-lists = "^1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
griddler = "griddler.console:run"
