name: mkdocs_build
description: build mkdocs
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: pip install mkdocs-material mkdocstrings "mkdocstrings[python]" mdx-truly-sane-lists
      shell: bash
    - run: mkdocs build
      shell: bash
