name: mkdocs
on:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      page_artifact_id: ${{ steps.upload.outputs.artifact_id }}
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - run: uv sync --locked --all-extras --all-groups
      - run: uv run mkdocs build --strict
      - uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: site
          retention-days: "3"

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          preview: false
